name: Build and deploy ASP.Net Core app to Azure Web App - fireguardai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore FireGuard_Backend/FireGuard_Backend.sln

      - name: Build
        run: dotnet build FireGuard_Backend/FireGuard_Backend.sln --configuration Release --no-restore

      - name: Publish API
        run: dotnet publish FireGuard_Backend/FireGuard.API/FireGuard.API.csproj -c Release -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fireguard-api
          path: publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fireguard-api
          path: publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D58BFC6D7DEE4B3D9AE91564ED650042 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_83CD4BAFB198435BAA9F2D6668E97B9A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_84571EECCD56444EA93AF4AA1981DB35 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: fireguardai
          slot-name: Production
          package: publish
